### ISSUE TITLE
withSpinner not compatible with rendering in server

### ISSUE THREAD

**Issue by dalekube** [andrewsali/shinycssloaders#14]
I utilize `modalDialog()` in the server to have a screen pop-up with a visualization. The server includes a `modalDialog(renderPlot())` call, and the `plotOutput()` UI element is not included/necessary. The `withSpinner()` function is not compatible as a wrapper to `renderPlot()`. For example, I cannot use `modalDialog(withSpinner(renderPlot()))`. The following error message is produced: 

> Warning: Error in as.vector: cannot coerce type 'closure' to vector of type 'character'

Is there any workaround or hack to making this work?

**Comment by andrewsali** [comment]
What if you do: `modalDialog(withSpinner(tagList(renderPlot())))` ?

If this works, one more recommendation: make sure you use the github version of `shinycssloaders` with `modalDialog`, it will work better than the one on CRAN.

**Comment by dalekube** [comment]
Yes, that works! Thank you. I had no idea tagList could be used like that.
