### ISSUE TITLE
Prevent spinner.js console.log output

### ISSUE THREAD

**Issue by trafficonese** [andrewsali/shinycssloaders#26]
The actual CRAN version of `shinycssloaders` has a `console.log` output in `spinner.js`

I just saw that this line is not there anymore in the github-version. So I just wanted to ask, when you we're goign to deploy a new version to CRAN?

**Comment by daattali** [comment]
I'm wondering about this as well

**Comment by dylancis** [comment]
same here

**Comment by daattali** [comment]
On CRAN now
