### ISSUE TITLE
Suggestion: remove all files and dirs from inst/css-loaders and only keep the CSS

### ISSUE THREAD

**Issue by daattali** [andrewsali/shinycssloaders#38]
It seems that `inst/css-loaders` contains the entire css spinners' github repo. But as far as I can tell, only the css files are needed and it not only bloats the repo with unnecessary files, but it also confuses potential contributors (such as myself, it took me some time to convince myself that I don't need to touch the less and sass files and use grunt)

**Comment by andrewsali** [comment]
Yes, definitely a good idea!
