### ISSUE TITLE
Ids of html elements are logged in console with each change of value

### ISSUE THREAD

**Issue by mturbasa** [andrewsali/shinycssloaders#6]
Please remove line 11 in spinner.js.

**Comment by andrewsali** [comment]
This should already be fixed in the github version - I hadn't had time to update the CRAN version yet. Can you please try by installing via `devtools::install_github` as specified in the readme?

**Comment by mturbasa** [comment]
Yeah, you are right. Sorry, it's already fixed in the github version.

**Comment by daattali** [comment]
On CRAN now
